### ISSUE TITLE
Pb opening image

### ISSUE THREAD

**Issue by mcib3d** [GReD-Clermont/simple-omero-client#69]
Hi,

With newer versions 5.12 and 5.14 I there is an error when I try  to open an image with `ImageWrapper.toImagePlus`. The error is : 
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/java.util.Optional.of(Optional.java:113)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:194)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:191)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at fr.igred.omero.meta.PlaneInfoWrapper.computeMeanTimeInterval(PlaneInfoWrapper.java:74)
	at fr.igred.omero.repository.PixelsWrapper.getMeanTimeInterval(PixelsWrapper.java:217)
	at fr.igred.omero.repository.ImageWrapper.setCalibration(ImageWrapper.java:114)
	at fr.igred.omero.repository.ImageWrapper.toImagePlus(ImageWrapper.java:666)
	at fr.igred.omero.repository.ImageWrapper.toImagePlus(ImageWrapper.java:614)
	at mcib3d.tapas.plugins.Omero_Read.run(Omero_Read.java:75)
```
I have no error with version 5.9.

Thanks.

**Comment by mcib3d** [comment]
It seems to have something to do with _Exposure Time_ in the metadata. I can open some images but not all of them.

**Comment by ppouchin** [comment]
Ok. I guess there are null values in the deltas somehow. I'll fix it by tomorrow.
Would you have a sample image with the wrong metadata by chance, so I can make sure it works?

**Comment by ppouchin** [comment]
I may have a [fix](https://github.com/GReD-Clermont/simple-omero-client/compare/main...69-null-deltas).

**Comment by ppouchin** [comment]
@mcib3d I may have a [fix](https://github.com/GReD-Clermont/simple-omero-client/compare/main...69-null-deltas).
